---
- hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: install kubectl
      ansible.builtin.get_url: 
        url: https://dl.k8s.io/release/v1.28.2/bin/linux/amd64/kubectl
        dest: /usr/bin/
        mode: +x
    - name: install aws
      ansible.builtin.get_url: 
        url: https://github.com/stern/stern/releases/download/v1.26.0/stern_1.26.0_linux_amd64.tar.gz 
        dest: /usr/bin/stern
        mode: +x
