---
# terraform code no presente paquete por defecto
- hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Install required system packages
      apt:
        state: latest
        update_cache: yes
        name:
         - apt-transport-https

    - name: Install the Helm GPG key.
      apt_key:
        url: https://baltocdn.com/helm/signing.asc 
        keyring: /usr/share/keyrings/helm.gpg
        state: present

    - name: Add the Repo Helm
      apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
        state: present
        filename: helm-stable-debian

    - name: Install Helm
      apt:
       state: present
       update_cache: true
       name:
        - helm 

