- hosts: localhost
  become: yes
  become_user: root
  vars:
    current_user: "{{ lookup('env','USER') }}"
  roles:
    - role: devops
      when: install_devops
    - role: virtualization
      when: install_virtualization
    - role: utilities
      when: install_utilities