---
- hosts: localhost
  become: true
  become_user: root
  tasks:
    # - name: Include tasks install docker 
    #   ansible.builtin.include_tasks:
    #     file: tasks/docker.yaml

    # - name: Include tasks install terraform 
    #   ansible.builtin.include_tasks:
    #     file: tasks/terraform.yaml

    # - name: Include tasks install terraform 
    #   ansible.builtin.include_tasks:
    #     file: tasks/vagrant.yaml

    # - name: Include tasks install k8s tools 
    #   ansible.builtin.include_tasks:
    #     file: tasks/k8s_tools.yaml

    # - name: Include tasks install helm 
    #   ansible.builtin.include_tasks:
    #     file: tasks/other.yaml

    # - name: Install oh-my-zsh package.
    #   shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    
    - name: Include tasks install AWS cli 
      ansible.builtin.include_tasks:
        file: tasks/aws_cli.yaml