- name: Include tasks install helm 
  ansible.builtin.include_tasks:
    file: tasks/helm.yaml

- name: install minikube
  apt:
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb

- name: install kubectl
  ansible.builtin.get_url: 
    url: https://dl.k8s.io/release/v1.29.2/bin/linux/amd64/kubectl
    dest: /usr/bin/
    mode: +x

- name: autocomplete and alias kubectl.
  shell: |
    echo 'alias k=kubectl' >>/home/akira/.zshrc
    echo 'compdef __start_kubectl k' >>/home/akira/.zshrc

- name: Download the stern.
  get_url: url=https://github.com/stern/stern/releases/download/v1.26.0/stern_1.26.0_linux_amd64.tar.gz dest=/tmp/stern_1.26.0_linux_amd64.tar.gz
  register: stern_linux_binary

- name: Unarchive and copy the stern installer.
  unarchive: src=/tmp/stern_1.26.0_linux_amd64.tar.gz dest=/usr/bin copy=no creates=/usr/bin/stern
  when: stern_linux_binary.changed
  register: stern_linux_binary