# - name: install zsh
#   apt:
#     state: present
#     update_cache: yes
#     name:
#       - zsh

# - name: Download ohmyzsh
#   ansible.builtin.get_url:
#     url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
#     dest: "/tmp/install.sh"

# - name: Install ohmyzsh
#   ansible.builtin.script:
#     cmd: "/tmp/install.sh"
#   # ignore_errors: true
    