---
# https://github.com/xchangebit/ansible-aws-cli/blob/master/tasks/main.yml
- name: Install package dependencies.
  package: name={{ item }} state=present
  with_items:
    - python3
    - unzip

- name: Download the awscli v2.
  get_url: url=https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip dest=/tmp/awscliv2.zip
  register: aws_cli_download_bundle

- name: Unarchive the installer.
  unarchive: src=/tmp/awscliv2.zip dest=/tmp copy=no creates=/tmp/awscliv2
  when: aws_cli_download_bundle.changed
  register: aws_cli_unarchive_installer

- name: Install awscli package.
  shell: /tmp/aws/install
  when: aws_cli_unarchive_installer.changed
